### PR TITLE
helper functions + demo of nmdc json etl to mongo

### PR DESCRIPTION
**Pull request by dwinston**

### CODE REVIEW

**Comment by wdduncan** [comment]
Why is mongo utils in the `schema` directory?

**Review by wdduncan — APPROVED** [review]
You can merge

**Comment by dwinston** [comment]
I was originally thinking of putting the helper utils in a python file, but I think it's fine for them to live in the notebook for now.

**Comment by wdduncan** [comment]
You can put the helper functions in a`notebooks/lib` directory too.

**Pull request merged**
