### PR TITLE
fixing mapping table; fixes #95

### LINKED ISSUE #95: gold to mixs mapping table contains syntax errors
```
$ grep '?' ./metadata-translation/src/data/GOLD-to-mixs-map.tsv 
gold    biosample       soil_annual_season_temp season_temp or annual_temp?
gold    biosample       soil_annual_season_precpt       season_precpt or annual_precpt?
```

the value of c4 should be a single atomic string. Information such as certainty should be indicated in a separate field. If a mapping is not one to one consider using a scheme like skos/sssom to explicitly distinguish exact/1:1 from imprecise

### PR DESCRIPTION
**Pull request by cmungall**

### CODE REVIEW

**Comment by wdduncan** [comment]
Do you want me to merge? Thanks for fixing "flooding". I need to check to Jagadish about the other issues I raised in the other PR.

**Comment by cmungall** [comment]
comment from @wdduncan on other PR:

The reason for the fields that look like:

soil_annual_season_temp or season_temp or annual_temp?
season_precpt or annual_precpt?
is b/c we don't know what the correct mixs term should be. Should gold:soil_annual_season_temp map to mixs:season_temp or mixs:annual_temp. Should gold:soil_annual_season_precpt map to mixs:season_precpt or mixs:annual_precpt?

My answer:

use SSSOM and indicate uncertaintly using appropriate fields

This PR is an intermediate step and at least makes the tsv machin interpretable

**Comment by wdduncan** [comment]
> use SSSOM and indicate uncertaintly using appropriate fields
What would the SSSOM predicate would be?

**Comment by cmungall** [comment]
skos:exactMatch for exact, anything else eg skos:close or broadMatch for inexct

**Pull request merged**
